project:
  type: website
  output-dir: "./_site/en"

website:
  title: "Putting into production course"
  navbar:
    collapse-below: lg
    left:
      - href: https://ensae-reproductibilite.github.io/
        text: Putting into production
      - href: chapters/introduction.qmd
        text: Introduction
      - text: Fundamentals
        menu:
          - href: chapters/linux101.qmd
            text: Linux 101
          - href: chapters/git.qmd
            text: Git
      - text: Good development practices
        menu:
          - href: chapters/code-quality.qmd
            text: Code quality
          - href: chapters/projects-architecture.qmd
            text: Projects structure
          - href: chapters/big-data.qmd
            text: Big data
          - href: chapters/portability.qmd
            text: Portability
      - text: Putting into production
        menu:
          - href: chapters/yaml101.qmd
            text: YAML 101
          - href: chapters/deployment.qmd
            text: Deployment
          - href: chapters/mlops.qmd
            text: MLOps
      - href: chapters/application.qmd
        text: Application
      - text: Projects
        menu:
          - href: chapters/evaluation.qmd
            text: Evaluations
          - href: chapters/galerie.qmd
            text: Past student projects
      - icon: github
        menu:
          - text: Website
            url:  https://github.com/ensae-reproductibilite/website
          - text: Slides
            url:  https://github.com/ensae-reproductibilite/slides
          - text: Red thread application
            url:  https://github.com/ensae-reproductibilite/application
