[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.83.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"


[[redirects]]
  from = "https://ensae-reproductibilite.netlify.app/*"
  to = "https://linogaliana.github.io/ensae-reproductibilite-website/:splat"
  status = 301
  force = true
