::: {.application}
## Application 18: Mettre à disposition l'API (déploiement manuel)

Cette partie nécessite d'avoir à disposition une infrastructure _cloud_.

- Créer un dossier `deployment` à la racine du projet qui va contenir les fichiers de configuration nécessaires pour déployer sur un cluster `Kubernetes`

- En vous inspirant de la [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment), y ajouter un premier fichier `deployment.yaml` qui va spécifier la configuration du *Pod* à lancer sur le cluster

<details>
<summary>Fichier `deployment/deployment.yaml`</summary>

```{.python filename="deployment/deployment.yaml"}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-deployment
  labels:
    app: titanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
      - name: titanic
        image: votre_compte_docker_hub/application:latest #<1>
        ports:
        - containerPort: 8000
1. Remplacer ici par votre compte Docker
```

</details>

- En vous inspirant de la [documentation](https://kubernetes.io/fr/docs/concepts/services-networking/service/#d%C3%A9finition-d-un-service), y ajouter un second fichier `service.yaml` qui va créer une ressource `Service` permettant de donner une identité fixe au `Pod` précédemment créé au sein du cluster

<details>
<summary>Fichier `deployment/service.yaml`</summary>

```{.yaml filename="deployment/service.yaml"}
apiVersion: v1
kind: Service
metadata:
  name: titanic-service
spec:
  selector:
    app: titanic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
```
</details>

- En vous inspirant de la [documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource), y ajouter un troisième fichier `ingress.yaml` qui va créer une ressource `Ingress` permettant d'exposer le service via une URL en dehors du cluster

<details>
<summary>Fichier `deployment/ingress.yaml`</summary>

```{.python filename="deployment/ingress.yaml"}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titanic-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - votre_nom_d_application.lab.sspcloud.fr #<1>
  rules:
  - host: votre_nom_d_application.lab.sspcloud.fr #<2>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: titanic-service
            port:
              number: 80
```
1. Mettez l'URL auquel vous voulez exposer votre service. Sur le modèle de `titanic.lab.sspcloud.fr` (mais ne tentez pas celui-là, il est déjà pris 😃)
2. Mettre cette même URL ici aussi
</details>

- Appliquer ces fichiers de configuration sur le cluster : `kubectl apply -f deployment/`

- Vérifier le bon déploiement de l'application (c'est à dire du `Pod` qui encapsule le conteneur) à l'aide de la commande `kubectl get pods`. Regarder les _logs_ avec `kubectl logs -l app=titanic -f --tail=200`. Comprenez vous la source de l'erreur ?

- Créer un secret pour votre jeton d'API. Il y a plusieurs manières de faire. En l'occurrence, vous pouvez utiliser cette commande

```{.bash filename="terminal"}
kubectl create secret generic api-jeton --from-literal=JETON_API='mon_super_jeton'
```

- Mettre à jour votre _deployment_ pour indiquer à Kubernetes (le seul avec vous à connaître la valeur derrière le jeton):

```{.python}
#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-deployment
  labels:
    app: titanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
      - name: titanic
        image: votre_compte_docker_hub/application:latest #<1>
        ports:
        - containerPort: 8000
        env:
        - name: JETON_API
          valueFrom:
            secretKeyRef:
              name: api-jeton
              key: JETON_API
```
1. Remplacer ici par votre compte Docker

- Si tout a correctement fonctionné, vous devriez pouvoir accéder depuis votre navigateur à l'API à l'URL spécifiée dans le fichier `deployment/ingress.yaml`. Par exemple `https://api-titanic-test.lab.sspcloud.fr/` si vous avez mis celui-ci plus tôt.

- Explorer le *swagger* de votre API à l'adresse `https://api-titanic-test.lab.sspcloud.fr/docs`. Il s'agit d'une page de documentation standard à la plupart des APIs, bien utiles pour tester des requêtes de manière interactive. Regarder les _logs_ avant/après avoir testé les exemples interactifs d'utilisation. 

:::


{{< checkpoint appli18 >}}

