::: {.application}
## Application 2: rendre lisible le script

- Diagnostiquer et évaluer la qualité de `titanic.py` avec [`PyLint`](https://pylint.readthedocs.io/en/latest/). Regarder la note obtenue.
- Utiliser le formatter [ruff](https://docs.astral.sh/ruff/) via la commande `ruff check titanic.py` pour voir les problèmes recensés par celui-ci. Appliquer l'option `--fix` suggérée pour commencer à formatter le fichier. Evaluer à nouveau ce fichier avec [`PyLint`](https://pylint.readthedocs.io/en/latest/). 
- Utiliser `ruff format titanic.py` pour modifier la mise en forme du fichier. 
- Réutiliser [`PyLint`](https://pylint.readthedocs.io/en/latest/) pour diagnostiquer l'amélioration de la qualité du script et le travail qui reste à faire.
- Comme la majorité du travail restant est à consacrer aux imports:
    - Mettre tous les _imports_ ensemble en début de script
    - Retirer les _imports_ redondants en s'aidant des diagnostics de votre éditeur
    - Réordonner les _imports_ si [`PyLint`](https://pylint.readthedocs.io/en/latest/) ou  vous indique de le faire
    - Corriger les dernières fautes formelles suggérées par [`PyLint`](https://pylint.readthedocs.io/en/latest/)
- Délimiter des parties dans votre code pour rendre sa structure plus lisible. Si des parties vous semblent être dans le désordre, vous pouvez réordonner le script (mais n'oubliez pas de le tester)

<!-----
Temps test Julien: 22mn
------>
:::

{{< checkpoint appli2 >}}


