::: {.application}

## Application 13: création de l'image `Docker`

Se placer dans un environnement avec `Docker`, par
exemple _[Play with Docker](https://labs.play-with-docker.com)_

#### Création du `Dockerfile`

- Dans le terminal `Linux`, cloner votre dépôt `Github`
- Repartir du dernier _checkpoint_ mis à disposition (ou de votre dernière version si vous la préférez). 

- Créer via la ligne de commande un fichier texte vierge nommé `Dockerfile` (la majuscule au début du mot est importante)

<details><summary>Commande pour créer un `Dockerfile` vierge depuis la ligne de commande</summary>
```{.bash filename="terminal"}
touch Dockerfile
```
</details>

- Ouvrir ce fichier via un éditeur de texte et copier le contenu suivant dedans:

<details><summary>Premier `Dockerfile`</summary>

```{.bash filename="terminal" no-prefix=true}
FROM ubuntu:22.04

# Install Python
RUN apt-get -y update && \
    apt-get install -y python3-pip curl

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin/:$PATH"

# Install project dependencies
COPY pyproject.toml .
RUN uv sync

CMD ["uv", "run", "main.py"]
```
</details>

#### Construire (_build_) l'image

- Utiliser `docker build` pour créer une image avec le tag `my-python-app`

```{.bash filename="terminal"}
docker build . -t my-python-app
```

- Vérifier les images dont vous disposez. Vous devriez avoir un résultat proche de celui-ci :

```{.bash filename="terminal"}
docker images
```

```{.python}
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
my-python-app   latest    e83445c6fb5a   12 seconds ago   978MB
```

#### Tester l'image: découverte du cache

L'étape de `build` a fonctionné: une image a été construite.

Mais fait-elle effectivement ce que l'on attend d'elle ?

Pour le savoir, il faut passer à l'étape suivante, l'étape de `run`.

```{.bash filename="terminal"}
docker run -it my-python-app
```

```{.python}
python3: can't open file '/~/titanic/main.py': [Errno 2] No such file or directory
```

Le message d'erreur est clair : `Docker` ne sait pas où trouver le fichier `main.py`. D'ailleurs, il ne connait pas non plus les autres fichiers de notre application qui sont nécessaires pour faire tourner le code, par exemple le dossier `src`.

- Avant l'étape `CMD`, copier les fichiers nécessaires sur l'image afin que l'application dispose de tous les éléments nécessaires pour être en mesure de fonctionner.

<details>
<summary>Nouveau `Dockerfile` </summary>

```{.bash filename="terminal" no-prefix=true}
FROM ubuntu:22.04

# Install Python
RUN apt-get -y update && \
    apt-get install -y python3-pip curl

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin/:$PATH"

# Install project dependencies
COPY pyproject.toml .
RUN uv sync

COPY main.py .
COPY src ./src
CMD ["uv", "run", "main.py"]
```

</details>

- Refaire tourner l'étape de `build`

- Refaire tourner l'étape de `run`. Il vous manque la variable d'environnement `JETON_API` qui n'a pas été insérée dans le conteneur pour ne pas prendre le risque de la révéler. Il va falloir l'introduire au moment du _run_ avec la commande suivante: 

```{.python}
docker run -e JETON_API='' -it my-python-app
```

- A ce stade, l'application doit tourner de A à Z 🎉.
Félicitations, vous avez créé votre première application reproductible !

:::

::: {.callout-note}

Ici, le _cache_ permet d'économiser beaucoup de temps. Par besoin de
refaire tourner toutes les étapes, `Docker` agit de manière intelligente
en faisant tourner uniquement les étapes qui ont changé.

:::


{{< checkpoint appli13 >}}

