::: {.application}
## Application 25b (optionnelle) : `Github Actions` comme ordonnanceur

Pour que `Github` sache où aller écrire les _logs_ et les artefacts des entraînements, on va devoir lui indiquer où se trouve `MLFlow` et comment s'y identifier. Il va donc falloir lui donner un certain nombre de variables d'environnement. Il est __hors de question de mettre celles-ci dans le code__. Heureusement, `Github` propose la possibilité de renseigner des _secrets_: nous allons utiliser ceux-ci.

1. Aller dans les paramètres de votre projet `GitOps` et dans la section `Secrets and variables`

2. Vous allez avoir besoin de créer les secrets suivants:
    * `MLFLOW_TRACKING_URI`
    * `MLFLOW_TRACKING_USERNAME`
    * `MLFLOW_TRACKING_PASSWORD`
    * `JETON_API`

Les valeurs à renseigner sont à récupérer à dans le `README` de votre service `MLFlow`, qui s'affiche quand vous cliquez sur le bouton `Ouvrir` depuis la page [Mes services](https://datalab.sspcloud.fr/my-services)


3. Reprendre ce modèle d'action à mettre dans votre dépôt `GitOps` (`.github/workflows/train.yaml` par exemple).

<details>
<summary>
Modèle d'action `Github`
</summary>


```{.python}
name: Titanic Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  start-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Start Pipeline
        run: echo "Starting pipeline"

  train-model:
    needs: start-pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model-config:
          - { n_trees: 10, max_features: "log2" }
          - { n_trees: 20, max_features: "sqrt" }
          - { n_trees: 20, max_features: "log2" }
          - { n_trees: 50, max_features: "sqrt" }
    container:
      image: compte_github/application:v0.0.4 #<1>
    env:
      MLFLOW_TRACKING_URI: "${{ secrets.MLFLOW_TRACKING_URI }}"
      MLFLOW_TRACKING_USERNAME: "${{ secrets.MLFLOW_TRACKING_USERNAME }}"
      MLFLOW_TRACKING_PASSWORD: "${{ secrets.MLFLOW_TRACKING_PASSWORD }}"
      MLFLOW_EXPERIMENT_NAME: "titanicml"
      JETON_API: "${{ secrets.JETON_API }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: 'compte_github/application' #<2>

      - name: Train Model
        run: |
          uv run train.py --n_trees=${{ matrix.model-config.n_trees }} --max_features=${{ matrix.model-config.max_features }}
```
1. Mettre votre image ici, issue de l'application précédente. Si vous n'en avez pas, vous pouvez mettre `linogaliana/application:v0.0.4`
2. On reprend le code applicatif de l'application précédente. Vous pouvez remplacer par votre dépôt et une référence adaptée si vous préférez

</details>

4. _Pusher_ et observer l'UI de `Github` depuis l'onglet `Actions`. Vous devriez retrouver @fig-pipeline-github dans celle-ci. Cliquer sur l'un des services et observer les _logs_ obtenus.

5. Retourner voir sur l'UI de MLFlow les nouveaux entraînements. 

:::
